name: IMSDK UAT Compilation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
      group: GHA-Framework-Stg-SelfHosted-RG
      labels:
        - self-hosted
        - framework-stg-u2404-x64-od-ephem

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        env:
          S3_WEBAPP_TOKEN: ${{ secrets.S3_WEBAPP_TOKEN }}
          SDK_OBJECT_URL: ${{ secrets.SDK_OBJECT_URL }}
        run: |
          chmod +x ci/build.sh
          ./ci/build.sh
      
      - name: Upload artifacts to S3 bucket
        uses: qualcomm-linux/upload-private-artifact-action@aws-v4
        with:
          path: $GITHUB_WORKSPACE/artifacts.tar.gz
          destination: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}/
          s3_bucket: qli-stg-framework-gh-artifacts
